#ifndef CLI_VAL_NATIVE_H
#define CLI_VAL_NATIVE_H

#include "magic/magic.h"

#define NATIVE_ADD(TYPE, V, OTHER_V) \
	((DEREF(TYPE, V) = DEREF(TYPE, V) + DEREF(TYPE, OTHER_V)), 1)

#define NATIVE_SUB(TYPE, V, OTHER_V) \
	((DEREF(TYPE, V) = DEREF(TYPE, V) - DEREF(TYPE, OTHER_V)), 1)

#define NATIVE_CMP(TYPE, V, OTHER_V) \
	COMPARE(DEREF(TYPE, V), DEREF(TYPE, OTHER_V))

#endif /* CLI_VAL_NATIVE_H */
